<template>
  <div><div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-3xl font-black">Stock</h1><p class="mt-1 text-sm text-slate-500">Stocks réels, y compris les écarts négatifs.</p></div><NuxtLink to="/admin/scanner" class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">📷 Scanner</NuxtLink></div>
    <div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th class="p-4">Produit</th><th>Code-barres</th><th>Catégorie</th><th>Stock</th><th>Actions</th></tr></thead><tbody><tr v-for="product in catalog.products" :key="product.id" class="border-t border-slate-100"><td class="p-4"><div class="flex items-center gap-3"><img :src="product.image" class="h-10 w-10 rounded-lg object-cover"><strong>{{ product.name }}</strong></div></td><td class="font-mono text-xs text-slate-500">{{ product.barcode }}</td><td class="text-slate-500">{{ labels[product.category] }}</td><td><span :class="product.stock <= 0 ? 'bg-red-50 text-red-700' : product.stock <= 5 ? 'bg-orange-50 text-orange-700' : 'bg-emerald-50 text-emerald-700'" class="rounded-full px-2.5 py-1 text-xs font-bold">{{ product.stock }}</span></td><td><div class="flex gap-2"><button class="rounded-lg bg-slate-100 px-2.5 py-1.5" @click="catalog.adjustStock(product.id, -1)">−1</button><button class="rounded-lg bg-slate-900 px-2.5 py-1.5 text-white" @click="catalog.adjustStock(product.id, 1)">+1</button><button class="rounded-lg bg-red-50 px-2.5 py-1.5 text-red-700" @click="catalog.setStock(product.id, 0)">Rupture</button></div></td></tr></tbody></table></div></div>
  </div>
</template>
<script setup lang="ts">
definePageMeta({ layout: "admin", middleware: ["auth"], permission: "stock.read" });
const catalog = useCatalogStore();
const labels = { drinks: "Boissons", snacking: "Snacking", essential: "Nécessaire", aperitif: "Apéro", grocery: "Épicerie" };
</script>