// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/1/2026, 4:31:54 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/jeydh/projects/nox-shop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeydh/projects/nox-shop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeydh/projects/nox-shop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeydh/projects/nox-shop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeydh/projects/nox-shop/plugins/**/*.{js,ts,mjs}","/home/jeydh/projects/nox-shop/composables/**/*.{js,ts,mjs}","/home/jeydh/projects/nox-shop/utils/**/*.{js,ts,mjs}","/home/jeydh/projects/nox-shop/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeydh/projects/nox-shop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/jeydh/projects/nox-shop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/jeydh/projects/nox-shop/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;